// this file was generated by scripts/generate_polymer_dependencies
// do not edit this file directly
// instead, edit the corresponding .html file and re-run the script
const {import_dom_modules} = require('libs_frontend/dom_utils')
require('bower_components/polymer-themes/ice.deps.js')
require('bower_components/paper-radio-group/paper-radio-group.deps.js')
require('bower_components/paper-radio-button/paper-radio-button.deps.js')
require('bower_components/paper-checkbox/paper-checkbox.deps.js')
import_dom_modules(require('components/difficulty-selector-4-hso.html'), 'components/difficulty-selector-4-hso.html')
require('components/difficulty-selector-4-hso')
